#!/bin/bash

cd frontend/
yarn run lint
read -p "Press [Enter] key to continue testing."
yarn test
read -p "Press [Enter] key to continue testing."
cd ../api/
yarn run lint
read -p "Press [Enter] key to continue testing."
yarn test
read -p "Press [Enter] key to finish testing."
cd ..
