// ------------------------- AUTH ------------------------------------------ //

export const USER_REQUEST = 'USER_REQUEST';
export const USER_RECEIVED = 'USER_RECEIVED';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
export const SET_AUTH_STATUS = 'SET_AUTH_STATUS';

// ------------------------- ERRORS ---------------------------------------- //

export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE';

// ------------------------- ARTIFACTS ------------------------------------- //

export const SET_STATUS_MESSAGE = 'SET_STATUS_MESSAGE';
export const UPDATE_ARTIFACT = 'UPDATE_ARTIFACT';
export const INITIALIZE_ARTIFACT = 'INITIALIZE_ARTIFACT';
export const ARTIFACTS_REQUEST = 'ARTIFACTS_REQUEST';
export const LOAD_ARTIFACTS_SUCCESS = 'LOAD_ARTIFACTS_SUCCESS';
export const LOAD_ARTIFACTS_FAILURE = 'LOAD_ARTIFACTS_FAILURE';
export const ARTIFACT_REQUEST = 'ARTIFACT_REQUEST';
export const LOAD_ARTIFACT_SUCCESS = 'LOAD_ARTIFACT_SUCCESS';
export const LOAD_ARTIFACT_FAILURE = 'LOAD_ARTIFACT_FAILURE';
export const EDIT_ARTIFACT_REQUEST = 'EDIT_ARTIFACT_REQUEST';
export const EDIT_ARTIFACT_SUCCESS = 'EDIT_ARTIFACT_SUCCESS';
export const EDIT_ARTIFACT_FAILURE = 'EDIT_ARTIFACT_FAILURE';
export const DOWNLOAD_ARTIFACT_REQUEST = 'DOWNLOAD_ARTIFACT_REQUEST';
export const DOWNLOAD_ARTIFACT_SUCCESS = 'DOWNLOAD_ARTIFACT_SUCCESS';
export const DOWNLOAD_ARTIFACT_FAILURE = 'DOWNLOAD_ARTIFACT_FAILURE';
export const VALIDATE_ARTIFACT_SUCCESS = 'VALIDATE_ARTIFACT_SUCCESS';
export const CLEAR_ARTIFACT_VALIDATION_WARNINGS = 'CLEAR_ARTIFACT_VALIDATION_WARNINGS';
export const SAVE_ARTIFACT_REQUEST = 'SAVE_ARTIFACT_REQUEST';
export const SAVE_ARTIFACT_SUCCESS = 'SAVE_ARTIFACT_SUCCESS';
export const SAVE_ARTIFACT_FAILURE = 'SAVE_ARTIFACT_FAILURE';

// ------------------------- TEMPLATES ------------------------------------- //

export const TEMPLATES_REQUEST = 'TEMPLATES_REQUEST';
export const LOAD_TEMPLATES_SUCCESS = 'LOAD_TEMPLATES_SUCCESS';
export const LOAD_TEMPLATES_FAILURE = 'LOAD_TEMPLATES_FAILURE';

// ------------------------- MODIFIERS ------------------------------------- //

export const CONVERSION_FUNCTIONS_REQUEST = 'CONVERSION_FUNCTIONS_REQUEST';
export const LOAD_CONVERSION_FUNCTIONS_SUCCESS = 'LOAD_CONVERSION_FUNCTIONS_SUCCESS';
export const LOAD_CONVERSION_FUNCTIONS_FAILURE = 'LOAD_CONVERSION_FUNCTIONS_FAILURE';

// ------------------------- VSAC ------------------------------------------- //

export const SET_VSAC_API_KEY = 'SET_VSAC_API_KEY';

// ------------------------- NAVIGATION ------------------------------------ //

export const SET_ACTIVE_TAB = 'SET_ACTIVE_TAB';
export const SET_SCROLL_TO_ID = 'SET_SCROLL_TO_ID';
