// ------------------------- AUTH ------------------------------------------ //

export const USER_REQUEST = 'USER_REQUEST';
export const USER_RECEIVED = 'USER_RECEIVED';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
export const SET_AUTH_STATUS = 'SET_AUTH_STATUS';

// ------------------------- ERRORS ---------------------------------------- //

export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE';

// ------------------------- ARTIFACTS ------------------------------------- //

export const SET_STATUS_MESSAGE = 'SET_STATUS_MESSAGE';
export const UPDATE_ARTIFACT = 'UPDATE_ARTIFACT';
export const INITIALIZE_ARTIFACT = 'INITIALIZE_ARTIFACT';
export const ARTIFACTS_REQUEST = 'ARTIFACTS_REQUEST';
export const LOAD_ARTIFACTS_SUCCESS = 'LOAD_ARTIFACTS_SUCCESS';
export const LOAD_ARTIFACTS_FAILURE = 'LOAD_ARTIFACTS_FAILURE';
export const ARTIFACT_REQUEST = 'ARTIFACT_REQUEST';
export const LOAD_ARTIFACT_SUCCESS = 'LOAD_ARTIFACT_SUCCESS';
export const LOAD_ARTIFACT_FAILURE = 'LOAD_ARTIFACT_FAILURE';
export const ADD_ARTIFACT_REQUEST = 'ADD_ARTIFACT_REQUEST';
export const ADD_ARTIFACT_SUCCESS = 'ADD_ARTIFACT_SUCCESS';
export const ADD_ARTIFACT_FAILURE = 'ADD_ARTIFACT_FAILURE';
export const EDIT_ARTIFACT_REQUEST = 'EDIT_ARTIFACT_REQUEST';
export const EDIT_ARTIFACT_SUCCESS = 'EDIT_ARTIFACT_SUCCESS';
export const EDIT_ARTIFACT_FAILURE = 'EDIT_ARTIFACT_FAILURE';
export const DELETE_ARTIFACT_REQUEST = 'DELETE_ARTIFACT_REQUEST';
export const DELETE_ARTIFACT_SUCCESS = 'DELETE_ARTIFACT_SUCCESS';
export const DELETE_ARTIFACT_FAILURE = 'DELETE_ARTIFACT_FAILURE';
export const DOWNLOAD_ARTIFACT_REQUEST = 'DOWNLOAD_ARTIFACT_REQUEST';
export const DOWNLOAD_ARTIFACT_SUCCESS = 'DOWNLOAD_ARTIFACT_SUCCESS';
export const DOWNLOAD_ARTIFACT_FAILURE = 'DOWNLOAD_ARTIFACT_FAILURE';
export const SAVE_ARTIFACT_REQUEST = 'SAVE_ARTIFACT_REQUEST';
export const SAVE_ARTIFACT_SUCCESS = 'SAVE_ARTIFACT_SUCCESS';
export const SAVE_ARTIFACT_FAILURE = 'SAVE_ARTIFACT_FAILURE';
export const PUBLISH_ARTIFACT_REQUEST = 'PUBLISH_ARTIFACT_REQUEST';
export const PUBLISH_ARTIFACT_SUCCESS = 'PUBLISH_ARTIFACT_SUCCESS';
export const PUBLISH_ARTIFACT_FAILURE = 'PUBLISH_ARTIFACT_FAILURE';
export const UPDATE_PUBLISH_ENABLED = 'UPDATE_PUBLISH_ENABLED';

// ------------------------- TEMPLATES ------------------------------------- //

export const TEMPLATES_REQUEST = 'TEMPLATES_REQUEST';
export const LOAD_TEMPLATES_SUCCESS = 'LOAD_TEMPLATES_SUCCESS';
export const LOAD_TEMPLATES_FAILURE = 'LOAD_TEMPLATES_FAILURE';

// ------------------------- RESOURCES ------------------------------------- //

export const RESOURCES_REQUEST = 'RESOURCES_REQUEST';
export const LOAD_RESOURCES_SUCCESS = 'LOAD_RESOURCES_SUCCESS';
export const LOAD_RESOURCES_FAILURE = 'LOAD_RESOURCES_FAILURE';

// ------------------------- VALUE SETS ------------------------------------- //

export const VALUE_SETS_REQUEST = 'VALUE_SETS_REQUEST';
export const LOAD_VALUE_SETS_SUCCESS = 'LOAD_VALUE_SETS_SUCCESS';
export const LOAD_VALUE_SETS_FAILURE = 'LOAD_VALUE_SETS_FAILURE';
